services:
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend
      - frontend

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env.prod.backend
    environment:
      UVICORN_HOST: 0.0.0.0
      UVICORN_PORT: 8000
    command: >
      sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 2"
    depends_on:
      - postgres
      - redis

  frontend:
    build:
      context: ./apps/frontend
    restart: unless-stopped
    env_file:
      - .env.prod.frontend
    environment:
      NODE_ENV: production
    command: npm run start
    depends_on:
      - backend

  postgres:
    image: postgis/postgis:16-3.4
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: socialmap
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped

volumes:
  pgdata:
  caddy_data:
  caddy_config:
