name: Deploy
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (metadata only)
        uses: actions/checkout@v4
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            set -e
            cd /opt/social-map
            if [ ! -d .git ]; then
              git clone ${{ secrets.REPO_CLONE_URL }} .
            else
              git fetch --all
              git reset --hard origin/main
            fi
            docker-compose -f docker-compose.prod.yml up -d --build
            docker image prune -f
